import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Preview from './preview'


const listingIds = [ 
  2931577, 
  24061603,
  51020624,
  20144835
];

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>RemoteBase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.fixed}>
          <h1 className={styles.title}>
            Prototypes for <a href="https://remotebase.co/">RemoteBase</a>
          </h1>

          <p className={styles.description}>
            Accommodation solutions for digital nomads by {' '}
            <code className={styles.code}>Chris Cerra</code>
          </p>
        </div>

        <div className={styles.body}>
    
        {listingIds.map(listingId => {
          return (
            <div className={styles.grid} key={listingId}>
              <Preview listingId={listingId} className={styles.card} />
            </div>

          )
        })}
        </div>
       
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.kristofhayes.me/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Prototypes by {' '}
          <code className={styles.code}>hayeskg</code>
        </a>
      </footer>
    </div>
  )
}
